kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: localhost:5001/chatapp-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: mongodb://root:admin@mongodb:27017/chatApp?authSource=admin&retryWrites=true&w=majority
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: jwt
        - name: PORT
          value: "5002"
