kind: Service
apiVersion: v1
metadata:
  name:  backend
  namespace: chat-app
spec:
  selector:
    app:  backend
  type:  ClusterIP
  ports:
  - name:  backend-port
    port:  5002
    targetPort:  5002